version: '3.8'

services:
  backend:
    build:
      context: ./springBootRestapi/test2/test2
      dockerfile: Dockerfile
    ports:
     - "8080:8080"  
    restart: unless-stopped 
    
  frontend:
    build:
      context: ./reactjs/test4api
      dockerfile: Dockerfile
    ports:
     - "5173:5173"     
    restart: unless-stopped 
    volumes:
      - ./reactjs/test4api/node_modules:/usr/app/node_modules
      - ./reactjs/test4api:/usr/app
    environment:
      - WATCHPACK_POLLONG=true
      




   